### ISSUE TITLE
ActivityPump Vocabulary and JSON-LD context

### ISSUE THREAD

**Issue by elf-pavlik** [w3c/activitypub#30]
It looks like AP defines new vocabulary terms e.g. properties: inbox, outbox, followers, followings. I would see need to define a namespace (even temporary) and create JSON-LD context which one would use together with AS 2.0 context. Should I make PR?

**Comment by cwebber** [comment]
I see what you're saying... yes, it does look like ActivityPump is defining an extension on the Actor type in that it provides new properties...

I guess one question is, what would this mean?  We can only have one implied context.  Would we want to add a @context object only to Actor objects only?  I don't think we have any other extensions, and I'm not sure if all objects need the @context.

**Comment by cwebber** [comment]
@elf-pavlik If you wanted to put together a preliminary @context, that might be really useful!

**Comment by wilkie** [comment]
One of the more interesting unique properties is "itemsType" on Collection. (Or is it "objectsType", it is unclear in "7.4 Streams") This is the kind of property such that if it is deemed useful in an implementation like ActivityPump should just be in AS proper. A Collection that contains only "as:Audio" or media ["as:Audio", "as:Video", "as:Image"] is a useful thing to know?

**Comment by cwebber** [comment]
@wilkie heh... I just removed the relevant text mentioning that section in 4d775d6 ...

**Comment by tsyesika** [comment]
We're not sure how to create a W3C namespace for a context. Can you help with this @sandhawke

**Comment by sandhawke** [comment]
If someone else can write the context file, I'm happy to put it in place.....

**Comment by cwebber** [comment]
I've written the [json-ld context file](https://github.com/w3c-social/activitypub/blob/gh-pages/activitypub-context.jsonld), but it needs to be put in place.  Help is appreciated! :)

**Comment by cwebber** [comment]
From the Face to Face meeting:

RESOLVED: We'll give until October 11 to find out if we can put these in AS2 vocab. If we can do that, we will. If not, I'll use AP's own namespace.

**Comment by cwebber** [comment]
(resolved as that decision doesn't mean this issue is closed ;))

**Comment by cwebber** [comment]
We're going to use ActivityStreams' vocabulary, as was established at last Face to Face meeting.  So we need to get those terms into the AS namespace, but that has its own issue, #132.
